id: D0A20E299
source: https://library.bdrc.io
source_file: null
initial_creation_type: input
imported: '2022-06-27T04:24:36+00:00'
last_modified: '2022-06-27T10:21:02.009313+00:00'
parser: null
source_metadata:
  bdrc-instance-id: W1KG13126
  creation_method: proofreading, annotation-transfer
  source: 
      base_file: 
        id: D3871/peking.txt  #<rkts_text_id>/<edition>
        initial_creation_type: input
      line_page_info: 
        id: I647D7CBC/I1KG13283  #<pecha_id>/<bdrc_image_group_id>
        initial_creation_type: OCR
  base:
    EE71:
      image_group_id: I1KG13283
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་བཞུགས་སོ།
      total_pages: 88
      order: 114
      base_file: EE71.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
